server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:certificates/divoptimizer3.jks
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: divoptimizer3_key

spring:
  application:
    name: DividendOptimizer3
  datasource:
    url: jdbc:mysql://localhost:3306/golem?userSSL=false
    username: root
    password: sea4me
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  security:
    cors: https://localhost:5003 

logging:
  level:
    org.springframework.security: trace
    
rsa:
  rsa-private-key: classpath:certificates/private.pem
  rsa-public-key: classpath:certificates/public.pem
  
  
#    url: jdbc:mysql://localhost:3306/golem?userSSL=false
#    username: root
#    password: sea4me
