server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:certificates/divoptimizer3.jks
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: divoptimizer3_key
  http2:
    enabled: true

spring:
  application:
    name: DividendOptimizer3

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/golem?useSSL=false&serverTimezone=UTC
    username: root
    password: sea4me
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000
      validation-timeout: 5000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  security:
    cors: https://localhost:5004
    headers:
      https:
        enabled: true
      cors: https://localhost:5004

logging:
  level:
    org.springframework.security: debug

rsa:
  rsa-private-key: classpath:certificates/private.pem
  rsa-public-key: classpath:certificates/public.pem

stripe:
  api.key: sk_test_...
